#!/usr/bin/bash
echo "test1\n"
curl -v -c cook.txt 'http://localhost:8008/d04/ex00/index.php';
echo "\n\n\n"
echo "test2 on soumet\n"
curl -v -b cook.txt 'http://localhost:8008/d04/ex00/index.php?login=sb&passwd=beeone&submit=OK';
echo "\n\n\n"
echo "test3 on recharge sans passer les valeurs\n"
curl -v -b cook.txt 'http://localhost:8008/d04/ex00/index.php';
echo "\n\n\n"
echo "test4 on enleve le cookie\n"
curl -v 'http://localhost:8008/d04/ex00/index.php';