#!/usr/bin/bash
echo "on suppr passwd\n"
rm /Users/xmoreau/Piscine_PHP/MyWebSite/Day04/private/passwd
echo "\n\n\n"
echo " on soumet le formulairet\n"
curl -d login=toto1 -d passwd=titi1 -d submit=OK 'http://localhost:8008/Day04/ex01/create.php';
echo "\n\n\n"
echo "on regarde passwd"
more /Users/xmoreau/Piscine_PHP/MyWebSite/Day04/private/passwd;
echo "\n\n\n"
echo "on reessaye de creer le meme"
curl -d login=toto1 -d passwd=titi1 -d submit=OK 'http://localhost:8008/Day04/ex01/create.php';
echo "\n\n\n"
echo "on reessaye de creer un second sans pwd"
curl -d login=toto2 -d passwd= -d submit=OK 'http://localhost:8008/Day04/ex01/create.php';