#!/usr/bin/bash
echo "on suppr passwd\n"
rm /Users/xmoreau/Piscine_PHP/MyWebSite/Day04/private/passwd
echo "\n\n\n"
echo " on cree un identifiant\n"
curl -d login=x -d passwd=21 -d submit=OK 'http://localhost:8008/Day04/ex01/create.php';
echo "\n\n\n"
echo "on le modifie"
curl -d login=x -d oldpw=21 -d newpw=42 -d submit=OK 'http://localhost:8008/Day04/ex02/modif.php';
echo "\n\n\n"
echo "on regarde passwd"
more /Users/xmoreau/Piscine_PHP/MyWebSite/Day04/private/passwd;
echo "\n\n\n"
echo "on modifie avec meme param "
curl -d login=x -d oldpw=21 -d newpw=42 -d submit=OK 'http://localhost:8008/Day04/ex02/modif.php';
echo "\n\n\n"
echo "on reessaye de creer sans contenur"
curl -d login=x -d oldpw=21 -d newpw= -d submit=OK 'http://localhost:8008/Day04/ex02/modif.php';