version: '2'
services:
  web:
    image: keopx/apache-php:7.0
    ports:
      - "8008:80"
    links:
      - mysql
    volumes:
      - /Users/xmoreau/Piscine_PHP/MyWebSite:/var/www/html
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./config/php/7.0/php.ini:/etc/php/7.0/apache2/php.ini
      - ./config/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    working_dir: /var/www/html
  mysql:
    image: keopx/mysql:5.5
    ports:
      - "3306:3306"
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xem_root
      - MYSQL_DATABASE=db_xem
      - MYSQL_USER=xem
      - MYSQL_PASSWORD=xem_pass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      - PMA_HOST=mysql

